apiVersion: apps/v1
kind: Deployment
metadata:
  name: zone-marker
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desired-zone-for-anti-affinity
  template:
    metadata:
      labels:
        app: desired-zone-for-anti-affinity
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
