apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-test-sa
  namespace: e2e-admin-ns
imagePullSecrets:
- name: registry-credentials  # Explicit secret reference
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding  
metadata:
  name: e2e-test-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: e2e-test-role
subjects:
- kind: ServiceAccount
  name: e2e-test-sa
  namespace: e2e-admin-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: e2e-test-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "namespaces", "persistentvolumes", "services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "get"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["*"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "use"]
  resourceNames: ["registry-credentials"]
---
apiVersion: v1
kind: Pod
metadata:
  name: cluster-tester-debug-pod
  namespace: e2e-admin-ns
  labels:
    wd_service: "cluster-tester"
spec:
  imagePullSecrets:
  - name: registry-credentials
  serviceAccountName: e2e-test-sa
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: debug-container
    image: antonbiz/cluster-tester-debug:1.46
    command: ["/busybox/sh", "-c", "sleep infinity & wait"]
    imagePullPolicy: Always
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
    volumeMounts:
    - name: temp-volume
      mountPath: /app/temp
  volumes:
  - name: temp-volume
    emptyDir: {}
  restartPolicy: Never
