apiVersion: apps/v1
kind: Deployment
metadata:
  name: zone-spread-example
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: myapp
      containers:
      - name: app-container
        image: nginx:alpine
        command: ["sh", "-c"]
        args: ["sleep 5 && while :; do echo '15^999999' | bc >/dev/null; done"]
        resources:
          requests:
            cpu: 200m